# Generated by Django 6.1.1 on 2026-10-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-updated_at']},
        ),
    ]
